### ISSUE TITLE
Complete sourcepath in the SF line of lcov.info is missing

### ISSUE THREAD

**Issue by KSchrage-SIT** [cenfun/playwright-coverage#1]
I followed the instructions and got coverage working as described. I noticed however, that the lcov.info is missing the full sourcepath of the specifiv files. It only lists the file name.

We get the following `SF:App.vue` instead of  `SF:src/App.vue`, for example. The ladder is generated from vitest/unit-tests.

Is there any configuration setting I can use here? It seems, that the information is somehow "there", since the generated html-report lists something like "http://localhost-3200/src/App.vue: App.vue".

**Comment by cenfun** [comment]
It is a common issue, We can resolve full path of the file with option `sourcePath` (issue https://github.com/cenfun/jest-monocart-coverage/issues/5)
```js
const path = require("path")

// MCR coverage options
{

    sourcePath: (filePath, info)=> {
        if (!filePath.includes('/') && info.distFile) {
            return `${path.dirname(info.distFile)}/${filePath}`;
        }
        return filePath;
    }
  
}
```
See [`sourcePath`](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#resolve-sourcepath-for-the-source-files)

**Comment by KSchrage-SIT** [comment]
Jeah, that looks better now. However I now have `SF:localhost-3200/src/App.vue` instead of `SF:/src/App.vue`. Stripping out the `localhost-3200` within the sourcePath-lambda, results in `SF:../../../../src/App.vue`. Do I have to combine this with baseDir or something like that? I double checked the result of the lambda and it returns with `/src/App.vue`.

**Comment by cenfun** [comment]
Try following
```js
const path = require("path")

// MCR coverage options
{

    sourcePath: (filePath, info)=> {

        const str = 'localhost-3200';
        if (filePath.startsWith(str)) {
            return filePath.slice(str.length);
        }

        if (!filePath.includes('/') && info.distFile) {
            return `${path.dirname(info.distFile)}/${filePath}`;
        }
        return filePath;
    }
  
}

```

**Comment by KSchrage-SIT** [comment]
Unfortunately that results in `SF:../../../../src/App.vue` aswell.

**Comment by cenfun** [comment]
That's weird.  But I can't help you unless you provide the reproduction steps

**Comment by KSchrage-SIT** [comment]
Here's the repro-case. Thanks for your help, really appreciate it.
[Archiv.zip](https://github.com/user-attachments/files/16621920/Archiv.zip)

**Comment by cenfun** [comment]
It seems that we need to remove `/`
```js
// previous
// const str = "localhost-3200";
// please change to

const str = "localhost-3200/";

```

```sh
TN:
SF:src\App.vue
FN:1,(anonymous_0)
```

**Comment by KSchrage-SIT** [comment]
That did the trick. Thanks!
